data/desktop/xfce4-floating-pomodoro.desktop usr/share/applications/
data/icons/hicolor/scalable/apps/xfce4-floating-pomodoro.svg usr/share/icons/hicolor/scalable/apps/
data/fonts/Manrope-Regular.ttf usr/share/xfce4-floating-pomodoro/fonts/
data/fonts/Manrope-SemiBold.ttf usr/share/xfce4-floating-pomodoro/fonts/
data/fonts/Manrope-Bold.ttf usr/share/xfce4-floating-pomodoro/fonts/
data/fonts/OFL.txt usr/share/doc/xfce4-floating-pomodoro/
